### ISSUE TITLE
libavahi-core-dev still needed?

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#112]
Lucid + Electric rosinstaller for Jenkins contained this dependency. What was/is using it?

**Comment by stonier** [comment]
Zeroconf.

It's probably breaking due to the change in rosdep1->rosdep2. With their new standards for rosdep2, the keyword changed from avahi->libavahi-core-dev. It's possible to make them compatible. Probably the easiest way of making this backwards compatible is by backporting the rosdep.yaml and manifest.xml in zeroconf_implementations master to electric and fuerte branches.

You can try it if you like, or if not - I'll do it when I get back next week.

**Comment by bit-pirate** [comment]
Well, Kobuki currently builds fine without libavahi. That is what made me wonder, why its there. Anyway, as long as everything works, we can tackle that next week.

**Comment by stonier** [comment]
zeroconf_avahi will fail to compile without that. Maybe that is not actually getting compiled. Or probably the server has already installed the deb (we don't sandbox properly -i.e. install debs and then uninstall debs).

**Comment by bit-pirate** [comment]
I uninstalled the deb manually to test that. So, I think zeroconf is not
compiled or sth else is happening.

2012/5/18 Daniel Stonier <
reply@reply.github.com

> zeroconf_avahi will fail to compile without that. Maybe that is not
> actually getting compiled. Or probably the server has already installed the
> deb (we don't sandbox properly -i.e. install debs and then uninstall debs).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/yujinrobot/kobuki/issues/112#issuecomment-5782745

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, Seoul, Republik Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, Seoul, Republic of Korea
주소: 대한민국 서울특별시 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de

**Comment by stonier** [comment]
I fixed the rosdeps...also rereleased ecl and zeroconf_implementations, but still sourcing them while they go through the release process. Should be ok.
