### ISSUE TITLE
Gazebo problems

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#142]
```
roslaunch turtlebot_gazebo turtlebot_empty_world.launch
```

This fails with a boost shared pointer problem. Uncommenting the inertial link for the base footprint (http://answers.ros.org/question/38465/fuerte-turtlebot-simulator-ubuntu-1204-precise/) fixes it, but introduces a kdl warning.

```
[ WARN] [1342746377.710425253]: The root link base_footprint has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
```

The resulting gazebo empty world is also blue (sky getting mixed up with the ground?).

Another problem:

```
Warning [RaySensor.cc:206] ranges not constructed yet (zero sized)
```

This is coming from turtlebot_gazebo's robot.launch (if you uncomment the include for that, the problem disappears).

**Comment by stonier** [comment]
We can work in the turtlebot stacks (they are now added to kobuki_unstable.rosinstall). 

When we identify problems, we should [ticket](http://kforge.ros.org/turtlebot/trac) them.

Once we're happy with fixes, let's commit them (use Daniel's account).

**Comment by bit-pirate** [comment]
OK, I tracked down the source of the KDL warning. The kdl_parser is responsible for this. There seems to be a design mismatch between KDL and Gazebo. The first can't handle inertia in the root link, the later now needs it. I say "now", because Gazebo in Electric was working fine without root link inertia.
I opened a ticket for the [KDL parser](https://kforge.ros.org/turtlebot/trac/ticket/138) and asked a question to the [Gazebo guys](https://bitbucket.org/osrf/gazebo/issue/4/failed-to-spawn-urdf-model-in-gazebo-if#comment-1709621). Let's see wait for responses there.
Also there has been a ticket for turtlebot about this already: https://kforge.ros.org/turtlebot/trac/ticket/138
Don't know about the blue world though.

**Comment by stonier** [comment]
The blue sea came in from a big update to the empty world file 3 months ago (this [diff](http://kforge.ros.org/turtlebot/simulator/rev/2ff182094fcc)).

Melonee also updated the xml tags to what seems to be a new gazebo style (big facelift).

I don't think this is a bug - rather just Melonee being funny.

**Comment by bit-pirate** [comment]
This has been fixed (see track tickets for details).
