### ISSUE TITLE
Robot naming

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#150]
Naming (launch, config etc. files) got a bit confusing with those many robots/combinations floating around.
My suggestion:
Create/Roomba + old stack -> "Turtlebot"
Kobuki (just the base) -> "Kobuki"
Kobuki + new stack -> "Turtlebot2"
iCreate/Roomba + new stack -> "Turtlebot1_5"
Kobuki + old stack -> ? (maybe not necessary)
and drop "Kobukibot"

Applying the above will break most/all launch files, since I will need to rename the urdf/xacros.
Any objections or remarks?

**Comment by bit-pirate** [comment]
Ok, naming confirmed. Will renaming the xacros and move turtlebot-specific files to the turtlebot repo.
Same for launch and maybe some config files.

**Comment by stonier** [comment]
Marcus, sorry for this - I was a bit snowed under last week and missed some of the details here.

Turtlebot2 I think we should just think of as the latest software (probably groovy+) running on whatever hardware (base or stacks) the user has got. Since the hardware is relatively swappable, what defines turtlebot 2 as turtlebot 2 is primarily software. I don't see anything wrong with a user running groovy on a create with old stacks and thinking about it as turtlebot 2 especially as the software will hopefully start getting a bump again.

Base and stack names should just be configurable options.

This is much the same as something like the linux kernel.

**Comment by bit-pirate** [comment]
I agree. But that leaves the naming issue unsolved again.
I would suggest using the naming scheme from above to allow new users an easy start. If someone uses a custom combination of stack, base & software, he probably is already proficient enough to put together on start files and doesn't worry about the naming (or choses an own name).

**Comment by stonier** [comment]
Done - component based naming, now implemented everywhere throughout turtlebot.
