### ISSUE TITLE
Node to Nodelet

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#166]
This would let people write their own reactive control nodelets (e.g. bumpers/cliff).

**Comment by bit-pirate** [comment]
Nodelet version is up and running. Example controller implementation still TODO

**Comment by corot** [comment]
Should we wrap rosconsole macros so we call NODELET_XXXX instead of ROS_XXXX?
What's the elegant way to do this?

**Comment by stonier** [comment]
Yes, they should all convert to NODELET_XXX now.

**Comment by bit-pirate** [comment]
Does NODELET_XXX actually work now? i'm remembering that there should be, but wasn't a difference in behaviour ...

**Comment by bit-pirate** [comment]
At the moment we make dual use of the KobukiROS library in nodelet and node. The only solution I can think of for keeping both is using DEFINEs to decide which logging macro should be used. Since we are thinking about using KobukiROS as nodelet only, this change can be obsolete. I'll fix this once we made a decision.

**Comment by stonier** [comment]
Obsolete :+1:  NODELET_XXX is a go.
