### ISSUE TITLE
Acceleration Jump on Starting

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#177]
Recreate with kobuki_keyop
- press up arrow, it launches
- disable, wait 5s, enable and up arrow again, it launches!

Alternatively
- press up arrow, it launches
- disable, enable, up arrow, disable enable, up arrow - it's smooth!

**Comment by stonier** [comment]
Also at http://redmine.yujin.com/issues/2296

**Comment by jakan2** [comment]
I checked fw, there are one magic to protect the motor driver circuit. So that i blocked pwm output for 100msec after motor power on. Consequently it has much i-term for the motor controller.
Please give me some time to discuss with hardware guy. 
Would you like to put the s-curve like velocity profile which start from lower velocity command until i found the good solution.

**Comment by jakan2** [comment]
- Action plan - root cause finding
  - Set zero dead time after first incoming velocity command
  - Observe motion with 0.05m/sec velocity command which causes issues before
- Action plan - to reduce dead time
  - Ask to hardware engineer about dead zone

**Comment by jakan2** [comment]
- Dead time causes high acceleration when it catch the first velocity command when motor is idle
  - when i set the small dead time, it works much better

**Comment by bit-pirate** [comment]
Einstein fixed it. The controller now starts, when the motor power is turned on (see firmware version 1.1.1).
