### ISSUE TITLE
Kobuki node dependency, kobuki_ftdi

### ISSUE THREAD

**Issue by stonier** [yujinrobot/kobuki#305]
It's not a compile dependency, nor a runtime dependency. But it's turning out to be a pain in the ass setup dependency. Everyone installs ros-hydro-turtlebot, which then causes a problem for people setting up the udev rule.

**Comment by corot** [comment]
Definitely better.  I update the installation tutorial accordingly.

**Comment by bit-pirate** [comment]
Maybe a comment in the package.xml explaining the reason of it being there
would be good - since we all lack of enough long-term memory...

2013/10/10 corot notifications@github.com

> Definitely better. I update the installation tutorial accordingly.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/yujinrobot/kobuki/issues/305#issuecomment-26019060
> .

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republik
Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republic
of Korea
주소: 대한민국 서울특별시 121-846 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de
