### ISSUE TITLE
"no events" pointcloud in kobuki_bumper2pc.cpp causes dropped events

### ISSUE THREAD

**Issue by KaijenHsiao** [yujinrobot/kobuki#332]
Using the pointcloud from kobuki_bumper2pc in my voxel layer today, I found that sometimes, no obstacle was being added to my global costmap.  Looking more closely into the point cloud that was being generated, I saw this:
[ INFO] [1406601457.191044109]: got a point cloud
[ INFO] [1406601457.191304917]: point 0 is 34.202 93.969 0.040
[ INFO] [1406601457.191356060]: point 1 is 0.400 0.000 0.040
[ INFO] [1406601457.191409016]: point 2 is 34.202 -93.969 0.040
[ INFO] [1406601457.212849109]: got a point cloud
[ INFO] [1406601457.213030352]: point 0 is 34.202 93.969 0.040
[ INFO] [1406601457.213066667]: point 1 is 34.202 0.000 0.040
[ INFO] [1406601457.213091182]: point 2 is 34.202 -93.969 0.040
and thought the point cloud must surely be broken, because why would there be three points full of nonsense and only most of the time the one point I needed?

Now that I've stared at kobuki_bumper2pc.cpp, I finally understand that that is the intended behavior.  Which should _really_ be explained somewhere!  But also, more importantly, if you have not set your bump observation source's observation_persistence param to a nonzero number (thus keeping more than just the one latest message in your observation buffer), you can lose the event entirely in your costmap, because _only the "no events"_ message gets kept while the others are dropped.

**Comment by corot** [comment]
Hi, kobuki_bumper2pc is intended to integrate the bumpers on navi stack (that is, reflect bumper contacts on costmaps_2d). And it's very simple: it just listen for bumpers state and, if a bumper is pressed, it publish the point near the robot, and if it's not pressed, it publish a faraway point so the costmaps using bumper data can be cleaned. So as you pointed, you can tweak the costmaps params to ensure persistence, with nonzero observation_persistence and setting clearing to false.

The problem you point comes, I think, from the fact that the pointclouds from kobuki_bumper2pc come at very high rate, much higher than update costmaps loop and, as the robot moves back after a hit (because of safety_controller) the  "no events" message comes very fast. I'm not fully sure, as I have been long time without hearing about this package.

**Comment by KaijenHsiao** [comment]
I guess my question is, is the "no events" message even necessary?  Under what circumstances would someone want to use it?  If it is not needed, removing it would eliminate the problem described.

**Comment by corot** [comment]
I think yes, because if not bumpers cannot clear the costmap. But I recognize that is not clear at all why a bumper should clear the costmap. I invite you to change the code to include a flag to disable "no events" messages and play around to see if it has a negative impact not removing the bumper hits from the costmaps.

But in the long rung, I think that the right solution is to replace this package by a sensor_msgs/Range publisher that publishes fixed-range range readings for each bumper/cliff. Thanks to the new package range_sensor_layer, it can be nicely integrated into navi stack.

**Comment by KaijenHsiao** [comment]
We actually use them in the no-clearing mode, and it works fine for us--with clearing + safety controller, it is often the case that the robot ends up bumping and bumping rather than re-planning to go around an obstacle.  However, I can see that someone might want it the other way.  I actually like having it in the Voxel layer as opposed to being Range messages, although I suppose it would be nice to have the option of either.
