### ISSUE TITLE
Is /odom filtered?

### ISSUE THREAD

**Issue by robograffitti** [yujinrobot/kobuki#351]
Hi, I would like to know whether /odom is an already filtered value or not.

Here, they said /odom is published but not sure because it is published from the nodelet.
http://answers.ros.org/question/41135/turtlebot-robot_pose_ekfodom-or-odom/

Sorry for not understanding from the source codes.
Let me double-check, please.

**Comment by mirzashah** [comment]
This is probably more appropriate for ros answers than an issue, but I'll bite.

You can see in the kobuki code that the position comes from wheel odometry and the yaw is taken directly from the built in IMU. This can be turned off to give pure raw wheel odometry by setting the 'use_imu' parameter to false.

This is where odometry is populated and published:
https://github.com/yujinrobot/kobuki/blob/indigo/kobuki_node/src/library/odometry.cpp#L91
https://github.com/yujinrobot/kobuki/blob/indigo/kobuki_node/src/library/slot_callbacks.cpp#L108

This is where odometry is computed in kobuki driver:
https://github.com/yujinrobot/kobuki_core/blob/indigo/kobuki_driver/src/driver/kobuki.cpp#L463

robot_pose_ekf (as of ros hydro) is NOT used by default in the provided kobuki launch files...what is being published to /odom is what kobuki_node is publishing above.  If you had an additional IMU or visual odometry and wanted to fuse it against the raw odom, simply run robot_pose_ekf and feed the kobuki odometry + your additional data and it will publish a smoothed odometry. You may also want to turn off 'publish_tf' in that case so that kobuki_node doesn't publish the the odom->base_link transform.

**Comment by bit-pirate** [comment]
:+1: 

ROS Answers would have been a good place for thi. @mirzashah 's answer would have gotten my upvote. :smile: 

Considering this done. @yoshimalucky and @mirzashah could you move both the question and answer to ROS Answers (and link to here)?

**Comment by robograffitti** [comment]
@mirzashah Thank you so much! That's exactly what I want to do. Also the last sentence is very helpful for expected struggle on my future way.
@bit-pirate Sorry for posting a question on inappropriate place. I was not sure which rosanswers or github. Let me move onto rosanswers.

**Comment by mirzashah** [comment]
@yoshimalucky no problem -- let me also add that the wheel encoders + gyro on the kobuki produce very good odometry on surfaces with good traction...you may not need to smooth the odometry further for your application
