### ISSUE TITLE
 error: ‘KEYCODE_RIGHT’ is not a member of ‘kobuki_msgs::KeyboardInput {aka kobuki_msgs::KeyboardInput_<std::allocator<void> >}’      case kobuki_msgs::KeyboardInput::KEYCODE_RIGHT:

### ISSUE THREAD

**Issue by 1046652786** [yujinrobot/kobuki#415]
i had changed the package name ,before i changed it was named kobuki_keyop, how can i solve it?

**Comment by antondim** [comment]
Had the same problem. Replacing the false values with the ones stated in http://docs.ros.org/hydro/api/kobuki_msgs/html/msg/KeyboardInput.html , did the trick for me .

For example, "KEYCODE_RIGHT" changes into "KeyCode_Right" etc etc.

Those values can be found in the source cpp file "keyop_core.cpp". 

Hope this helps.

**Comment by corot** [comment]
I changed kobuki_msgs/devel to match changes on devel here: b609a185e249d127679e7b18a24d606acbdf918f
So compiling latest devel together should work.

What are you trying to compile?

**Comment by rjam92** [comment]
Was this problem resolved? what was the installation process other than cloning this in catkin_ws/src and building it?

**Comment by stonier** [comment]
Problem I'm guessing is that you're using `devel` branch of `kobuki_keyop` which was part of an aborted ros2 migration.You should be using the release branch for melodic, which was `release/0.7-melodic` but it looks like @corot might have missed that one and has been working on `melodic`.

Actually, looks like there has been other fixes going into `devel`. I'd recommend:

* Cherry-picking any relevant fixes in `devel` to the `melodic` branch (since that is what is released on `ros/rosdistro`)
* Update the rosinstall to gather the appropriate melodic `release` branches, not `devel` branches
* Set `melodic` as the default branch
* Delete `devel` branch (make it clear we're only maintaining the ROS1 version)
* Delete `release/0.7-melodic` branch since it's redundant

**Comment by rjam92** [comment]
Just to make sure I am clear about what you are saying:
1. I should clone and build the melodic branch instead of the default devel branch 
2. Transfer any relevant fixes from devel branch to the melodic branch

If not so can you explain in more detail how to carry out the above steps? 
Thank you

Also,

I switched to the installation of release/0.7-melodic, downloaded the necessary kobuki_msgs and kobuki_core and now everything compiles through catkin_make. But when I connect it with kobuki and after adding myself to the kobuki dialout group and restarting the kobuki udev rules I still get:
[ WARN] [1597910913.321794544]: Kobuki : device does not (yet) available, is the usb connected?.
[ INFO] [1597910913.322511690]: Kobuki : device does not (yet) available on this port, waiting...
[ WARN] [1597910913.573889907]: Kobuki : no data stream, is kobuki turned on?

rosrun kobuki_ftdi create_udev_rules, executes without any errors but a /dev/kobuki is not created. 

Latest Update:
using the release/0.7-melodic, I have gotten things to work. Will update to melodic if you recommend it,

**Comment by stonier** [comment]
I'll send some PR's that cleanup the branch situation ...

-----

The connection problem sounds orthogonal.

* What do you get when you type `groups`? You usually have to log out/reboot to have the addition to the `dialout` group take affect.
* Do you see anything come up on `/dev/ttyUSB0` when you plug in kobuki?

**Comment by stonier** [comment]
Original problem here should be resolved with the PR above, closing out.
