### ISSUE TITLE
add kobuki_gazebo to kobuki_bringup dependency?

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/kobuki#98]
or keep both separate?

**Comment by stonier** [comment]
Doesn't really matter to me. It's a massive separate install, but the install unit is the stack, not the package, so when you install the stack, you'll bring it all in if it's a dependency of bringup or not.

If we really did want to separate it so that users can avoid that large install, we should create a new stack.

Does turtlebot have a different stack for gazebo related stuff?

**Comment by bit-pirate** [comment]
Yes, for turtlebot there is a separate stack for the Gazebo simulation. We could follow this structure.
stack: kobuki_simulator
packages: kobuki_gazebo, kobuki_gazebo_plugins,...
So, will we create a new repo in the Yujin account?

**Comment by stonier** [comment]
Do you think our gazebo stuff will evenutally merge with theirs or stay separate?

**Comment by stonier** [comment]
Having said that, I'm fine with another stack along very similar lines if you want to create it. Principle of least resistance for everybody who might want to use it/test it.

**Comment by bit-pirate** [comment]
Actually, we only need a gazebo controller plugin for kobuki (kobuki_gazebo_plugins) + some kobuki specific launch files (kobuki_gazebo). We could talk to the turtlebot guys, if we shouldnt add our controller plugin to the turtlebot_simulator stack.

**Comment by stonier** [comment]
Irrelevant now we're going to the merge. I'll open a separate issue for the kobuki gazebo plugin.
